package br.com.dio.todolist.dao

import androidx.room.*
import br.com.dio.todolist.model.Task

@Dao
interface TaskDAO {

    // Using return as Long allows to get ID generated by Room
    @Insert
    fun add(task: Task): Long

    @Query("SELECT * FROM Task ORDER BY id DESC")
    fun all(): List<Task>

    @Query("SELECT * FROM Task WHERE id=:id")
    fun get(id: Int): Task

    @Delete
    fun remove(task: Task)

    @Update
    fun edit(task: Task)
}